### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by diovudau** [aspiers/ly2video#108]
Hello.

I know you've written that your time is limited for this software project. But is there a chance for a new stable release?

**Comment by diovudau** [comment]
Now that there is so much active, I would like to repeat my question for a (github) release. This way linux distributions can make a package. They don't package from git. In fact, I want to create an Archlinux package.

**Comment by aspiers** [comment]
OK then: https://github.com/aspiers/ly2video/releases/tag/v0.5.0
