### ISSUE TITLE
same_quant error

### ISSUE THREAD

**Issue by kalegood** [aspiers/ly2video#44]
Most recent (as of 2/11/13) ffmpeg has depreciated same_quant and ly2video fails. 

I forget the specifics of what happened here. If I remember correctly, I had 1 file I created that worked; it was a single staff. When I added a staff, I got the same_quant error. 

Removing same_quant degraded video worked but degraded audio and video quality; fix was to insert -b:a 320 and -q 5

**Comment by ace214** [comment]
Hi, I'm getting this error again.

Option 'same_quant' was removed. If you are looking for an option to preserve the quality (which is not what -same_quant was for), use -qscale 0 or an equivalent quality factor option.
Failed to set value '1' for option 'same_quant': Invalid argument
Error parsing global options: Invalid argument

Pastebin: http://pastebin.com/P4yKjUn9

I'm on Arch (installed ly2video via AUR), ffmpeg v.2.6.1.

**Comment by aspiers** [comment]
As per above `same_quant` is no longer used in ly2video, so you must be using an old version.
