### ISSUE TITLE
Using an external audio track?

### ISSUE THREAD

**Issue by csillag** [aspiers/ly2video#63]
Hi, can I somehow make this work with an external audio track? (I an happy to manually provide timing information, in whatever format required.)

**Comment by aspiers** [comment]
Absolutely!  I've just documented it for you.

**Comment by csillag** [comment]
Thank you!

Two more related questions:

1. Can you please describe the required *input* format required by the [`xsc2beatmap`](../blob/master/xsc2beatmap), tool? (I might consider creating some other tool, besides `Transcribe!`, that can be used to create those files.)

2. How do I handle looped tracks? (Ie. when the same song is played twice, for example with two verses of lyrics.)

Thanks again.

**Comment by aspiers** [comment]
Sure, although in future it'd be great if you open one new issue per question just to keep things cleanly tracked.  It might also be acceptable to post them to the LilyPond users mailing list.

1. It wouldn't make sense for you to create a tool to generate `.xsc` files. They have all kinds of information which is specific to `Transcribe!` and completely irrelevant to `ly2video`.  Instead just write a tool which generates beatmap files directly.
2. Just ensure that your `.ly` source file results in a MIDI rendition which plays out the repeats.  ISTR that this should be possible, and is almost certainly mentioned somewhere in the LilyPond documentation.
