### ISSUE TITLE
Arch User Repository package has been deleted

### ISSUE THREAD

**Issue by Beacon515L** [aspiers/ly2video#64]
The AUR package ly2video has been deleted. I have retrieved it and some of its dependencies from the AUR Archive, tested them all, and taken over as maintainer of these packages.

The new AUR package is called [ly2video-git](https://aur.archlinux.org/packages/ly2video-git/).

**Comment by pl-gauthier** [comment]
Thanks @Beacon515L ! Nice job.

**Comment by aspiers** [comment]
Thanks for the info @Beacon515L. Is there an action for me here?  I'm not familiar with AUR.  For example is it worth updating the README to link to this new package?  If so, PRs are very welcome ;-)

**Comment by Beacon515L** [comment]
PR submitted. After merge, no action required.
