### ISSUE TITLE
ly2video.py referenced in readme is not included

### ISSUE THREAD

**Issue by GregoryREvans** [aspiers/ly2video#72]
Just found this repo, I use lilypond a lot and this seems like a useful project for both rehearsal tools and score follower videos. I'm trying to learn how to use this and I am little confused sorry!

I am having some trouble installing all of the dependencies on Mac OSX, which I'm certain I can work out later, but my *real* problem is that the `readme.md` file instructs to run a file called `ly2video.py` with the option `--help` in order to find usage information. The python file is not included in the repo so I was wondering where this is supposed to be?

Does this file get created as part of the installation process? If so, this may be why I can't find it anywhere on my machine. I'm sorry if I'm misunderstanding something.

Everything appears to install appropriately according to the terminal, but I look in my `virtualenv`'s python `site-packages` and none of the folders or files that were supposedly created are actually there.

**Comment by aspiers** [comment]
Thanks for the report @GregoryREvans - you are quite right that it should say to run `ly2video` not `ly2video.py`.  I'll fix this.
