### ISSUE TITLE
Switch to modern Pillow version

### ISSUE THREAD

**Issue by aspiers** [aspiers/ly2video#75]
Currently ly2video depends on Pillow 1.0 which is ancient and even has security vulnerabilities - not that that should matter for ly2video when it is used from the CLI, as there is no opportunity for privilege escalation.

However it should still be upgraded to work with the latest version.

**Comment by thawk** [comment]
It seems that the ``dependabot/pip/pillow-6.2.0`` branch is working well.

**Comment by aspiers** [comment]
Closed by #77.
