### ISSUE TITLE
Video frozen for the last part

### ISSUE THREAD

**Issue by thawk** [aspiers/ly2video#82]
For the last part of video, it doesn't scroll anymore, frozen at an image.  I guess adding an synchorization point at the end would help?

e.g. for file [I Believe.ly](https://github.com/aspiers/ly2video/files/4080254/I.Believe.txt), the video frozed at position near 15 seconds:

![frame449](https://user-images.githubusercontent.com/457419/72662126-3de3f180-3a1e-11ea-97c6-da6851d49bdd.png)

Debug log shows that there wasn't any image generated for the last 1344 ticks (6336 -> 7680).

```
        writing frame 394
        left edge at 13, cursor at 838
ticks: 5568 -> 6336 (768)
        beats from tick 5568 -> 6336: 2.000000 (384 ticks per beat)
        secs  from tick 5568 -> 6336: 1.818180 (66.000 bpm)
    secs at new tick 6336: 14.999985
    need next frameset to last 1.833318 secs
    need 54.999550 frames @ 30.000 fps
        writing frame 395
        left edge at 13, cursor at 839
...
        writing frame 448
        left edge at 13, cursor at 912
        writing frame 449
        left edge at 13, cursor at 914
.ticks: 6336 -> 7680 (1344)
------------------------------------------------------------
```

**Comment by aspiers** [comment]
There should have been MIDI events for the final notes, so some debugging is required to figure out what went wrong there.

**Comment by thawk** [comment]
I have found out that, python-ly doesn't recognize the ``\parallelMusic`` command.  So it failed to identify the correct octave.  Maybe we should close this issue.

**Comment by aspiers** [comment]
Or we could rename the issue to refer to lack of support for \parallelMusic.

**Comment by thawk** [comment]
It's better when I remove the \parallelMusic command.  But it seems that the issue is not fully solved, I think more time is needed to figure out it.

**Comment by thawk** [comment]
The issue is due to the lack of support for the ``\parallelMusic`` and ``\transpose`` command.  PR #85 solved this.
