### ISSUE TITLE
Dockerfile for ly2video

### ISSUE THREAD

**Issue by WeeSee** [aspiers/ly2video#88]
To make usage a lot easier, running ly2video should be available as docker image.

I‘d like to use it for simple songs and am highly interested in generating videos.

This Dockerfile should not be hard for someone with Python and Lilypond experience. 

Great repo!

**Comment by aspiers** [comment]
That's a great idea - don't have time to make one myself right now unfortunately, but I'd gladly accept a `Dockerfile` submission!
